config/routes.rb
Rails.application.routes.draw do
  resources :origamis
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'origamis#acerca'
  get 'acerca' => 'origamis#acerca'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/origami.rb
class Origami < ApplicationRecord
 mount_uploader :imagen, ImageUploader
 default_scope {order 'lower(nombre)'}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/origamis_controller.rb
class OrigamisController < ApplicationController
  before_action :set_origami, only: [:show, :edit, :update, :destroy]

  # GET /origamis
  # GET /origamis.json
  def index
    @origamis = Origami.all
  end

  # GET /origamis/1
  # GET /origamis/1.json
  def show
  end

  # GET /origamis/new
  def new
    @origami = Origami.new
  end

  # GET /origamis/1/edit
  def edit
  end

  # POST /origamis
  # POST /origamis.json
  def create
    @origami = Origami.new(origami_params)

    respond_to do |format|
      if @origami.save
        format.html { redirect_to @origami, notice: 'Origami was successfully created.' }
        format.json { render :show, status: :created, location: @origami }
      else
        format.html { render :new }
        format.json { render json: @origami.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /origamis/1
  # PATCH/PUT /origamis/1.json
  def update
    respond_to do |format|
      if @origami.update(origami_params)
        format.html { redirect_to @origami, notice: 'Origami was successfully updated.' }
        format.json { render :show, status: :ok, location: @origami }
      else
        format.html { render :edit }
        format.json { render json: @origami.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /origamis/1
  # DELETE /origamis/1.json
  def destroy
    @origami.destroy
    respond_to do |format|
      format.html { redirect_to origamis_url, notice: 'Origami was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_origami
      @origami = Origami.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def origami_params
      params.require(:origami).permit(:nombre, :dificultad, :categoria, :imagen)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/origamis_helper.rb
module OrigamisHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html manifest = "offline.appcache">
  <head>
    <title>Origamimobile</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    
    
    
 <div data-role="page" data-theme="a">
     <div data-role="header">
         <h1><%= yield :titulo %></h1>
         <%= yield :botones %>
     </div>
     <div class="ui-content" role="main">
     
<%= yield %>

     </div>

     <div data-role="footer" data-theme="a" data-position="fixed">
        <div data-role="navbar">
            <ul >
    <ul >

          <li> <%= link_to 'Nosotros', root_path,class: "ui-btn ui-btn-icon-top ui-icon-info #{ @origamis.present? ? '' : 'ui-btn-active'} ", data: {ajax: "false"} %></li>

          <li><%= link_to 'Origamis', origamis_path,  class: "ui-btn ui-btn-icon-top ui-icon-bars  #{ @origamis.present? && params[:favoritos].nil? ? 'ui-btn-active' : ''} " , data: {ajax: "false"} %></li>
          
          <li><%= link_to 'Origamis', origamis_path(favoritos: true),  class: "ui-btn ui-btn-icon-top ui-icon-star  #{ params[:favoritos].present? ? 'ui-btn-active' : ''} " , data: {ajax: "false"} %></li>></li>

    </ul>
            </ul>
        </div>

     </div>
 </div>

 <div data-role="page" id="acerca" data-theme="a">
     <div data-role="header" data-add-back-btn="true">
         <h1>Origami Mania</h1>
     </div>
     <div class="ui-content" role="main">
         <br>
         <div>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci aliquam architecto aspernatur debitis
             dolore doloremque ea eius error expedita facere fuga ipsum iusto laboriosam mollitia natus officiis
             perferendis placeat quaerat quas quasi quia rem sint sit tempora ut vitae, voluptatem!
         </div>

     </div>

     <div data-role="footer" data-theme="a" data-position="fixed">
         footer provisional....
     </div>
 </div>

    
    
  </body>
</html>

app/views/origamis/_form.html.erb
<%= form_with(model: origami, local: true, html: {multipart: true, "data-ajax" => "false"}) do |form| %>
  <% if origami.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(origami.errors.count, "error") %> prohibited this origami from being saved:</h2>

      <ul>
      <% origami.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :origami_nombre %>
  </div>

  <div class="field">
    <%= form.label :dificultad %>
    <%= form.text_field :dificultad, id: :origami_dificultad %>
  </div>

  <div class="field">
    <%= form.label :categoria %>
    <%= form.text_field :categoria, id: :origami_categoria %>
  </div>

  <div class="field">
    <%= form.label :imagen %>
    <%= form.file_field :imagen, id: :origami_imagen %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/origamis/acerca.html.erb
         <br>
         <div>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid dicta dolorem itaque nihil officiis
             rerum saepe sint voluptatem? Aliquam assumenda eum laboriosam laborum maiores minima nulla, odit omnis
             perferendis quaerat, reiciendis sequi sint sit ullam velit veniam vitae voluptatem voluptatum.
         </div>
         
 <%= content_for :titulo, "OrigamiMania" %>
 

app/views/origamis/edit.html.erb
<h1>Editing Origami</h1>

<%= render 'form', origami: @origami %>

<%= link_to 'Show', @origami %> |
<%= link_to 'Back', origamis_path %>

app/views/origamis/index.html.erb
<p id="notice"><%= notice %></p>
 <%= content_for :titulo, "Origamis" %>
 
 <%= content_for :botones do %>
   <%= link_to "nuevo", new_origami_path, class: "ui-btn ui-btn-right ui-corner-all ui-btn-icon-right ui-icon-plus ui-mini"%>
 <% end %>
 
          <form class="ui-filterable">
             <input id="filter-input" data-type="search">
         </form>

         <ul data-role="listview"
             data-autodividers="true"
             data-filter="true"
             data-input="#filter-input"
         >
         
           <% @origamis.each do |origami| %>
             <li class="ui-li-has-thumb">
               <%= link_to origami do %>
                 <%= image_tag(origami.imagen_url(:thumb)) if origami.imagen.present? %>
                 <h3><%= origami.nombre %></h3>
               <% end %>
             </li>
           <% end %>
             
             
          </ul>
   

app/views/origamis/new.html.erb
<h1>New Origami</h1>

<%= render 'form', origami: @origami %>

<%= link_to 'Back', origamis_path %>

app/views/origamis/show.html.erb
 <%= content_for :botones do %>
   <%= link_to "atras", origamis_path, {"data-rel"=>"back", class: "ui-btn ui-btn-left ui-corner-all ui-mini ui-btn-icon-left ui-icon-back  ui-btn-inline"}%>
 <% end %>

<%= content_for :titulo, @origami.nombre %>
<p id="notice"><%= notice %></p>



<p>
  <strong>Dificultad:</strong>
  <%= @origami.dificultad %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @origami.categoria %>
</p>

<p>
  <%= image_tag(@origami.imagen, id: "img-origami") if @origami.imagen.present? %>
</p>

	<div class="ui-grid-b ui-mini " id="showbotones">
		  <div class= "ui-block-a">
				<%= link_to "Favorito", @origami_path, {class: "ui-btn ui-icon-plus ui-btn-icon-top ui-btn-b ui-corner-all"} %>
		  </div>

		  <div class= "ui-block-b">
				<%= link_to "Editar", edit_origami_path(@origami), {class: "ui-btn ui-icon-info ui-btn-icon-top ui-btn-b ui-corner-all"} %>
		  </div>

		  <div class= "ui-block-c">
				<%= link_to "Eliminar", @origami_path, {data: {confirm: "¿estás seguro?"}, method: "delete", class: "ui-btn ui-icon-delete ui-btn-icon-top ui-btn-a ui-corner-all"} %>
		  </div>
	</div>

<%= link_to 'Edit', edit_origami_path(@origami) %> |
<%= link_to 'Back', origamis_path %>